### ISSUE TITLE
Announce Error

### ISSUE THREAD

**Issue by mayberks** [Matt-MX/AnnouncerVelocity#3]
It's an error I've been getting out of the blue lately. Nothing was changed, it suddenly stopped working.
```
[01:20:18] [Velocity Async Event Executor - #8/INFO]: Exception occurred while running command for Bycakr
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command vannouncer for [connected player] Bycakr (/IP)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command vannouncer for [connected player] Bycakr (/IP)
	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:223) ~[server.jar:3.1.2-SNAPSHOT (git-5ee96606-b136)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[server.jar:3.1.2-SNAPSHOT (git-5ee96606-b136)]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
Caused by: java.lang.IllegalStateException: Cannot send dev.simplix.protocolize.data.packets.OpenWindow to players with protocol version 758
	at dev.simplix.protocolize.velocity.player.VelocityProtocolizePlayer.sendPacket(VelocityProtocolizePlayer.java:54) ~[?:?]
	at dev.simplix.protocolize.api.player.ProtocolizePlayer.openInventory(ProtocolizePlayer.java:107) ~[?:?]
	at com.mattmx.announcer.util.gui.InventoryBuilder.open(InventoryBuilder.java:70) ~[?:?]
	at com.mattmx.announcer.commands.AnnounceCommand.execute(AnnounceCommand.java:55) ~[?:?]
	at com.mattmx.announcer.commands.AnnounceCommand.execute(AnnounceCommand.java:16) ~[?:?]
	at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[server.jar:3.1.2-SNAPSHOT (git-5ee96606-b136)]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[server.jar:3.1.2-SNAPSHOT (git-5ee96606-b136)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[server.jar:3.1.2-SNAPSHOT (git-5ee96606-b136)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[server.jar:3.1.2-SNAPSHOT (git-5ee96606-b136)]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
```

**Comment by Matt-MX** [comment]
Seems to be a version issue with Protocolize, not my problem.
