### ISSUE TITLE
Protocolize Issuse

### ISSUE THREAD

**Issue by xrh0905** [Matt-MX/AnnouncerVelocity#4]
Similar to https://github.com/Matt-MX/ServerGUI/issues/4
```
[14:38:27 ERROR] [Protocolize]: === EXCEPTION CAUGHT IN DECODER ===
[14:38:27 ERROR] [Protocolize]: Protocolize 2.2.2:445
[14:38:27 ERROR] [Protocolize]: Stream Direction: UPSTREAM
[14:38:27 ERROR] [Protocolize]: InboundConnection: [connected player] xrh0905 (/192.168.10.36:62827), ServerConnection: null
[14:38:27 ERROR] [Protocolize]: Protocol version: 1.19.1, 1.19.2
[14:38:27 ERROR]: java.lang.NoSuchMethodError: 'dev.simplix.protocolize.api.item.ItemStack dev.simplix.protocolize.api.inventory.InventoryClick.clickedItem()'
[14:38:27 ERROR]:       at com.mattmx.announcer.guis.AnnouncementsScreen.onClick(AnnouncementsScreen.java:86)
[14:38:27 ERROR]:       at dev.simplix.protocolize.data.listeners.ClickWindowListener.lambda$packetReceive$0(ClickWindowListener.java:48)
[14:38:27 ERROR]:       at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[14:38:27 ERROR]:       at dev.simplix.protocolize.data.listeners.ClickWindowListener.packetReceive(ClickWindowListener.java:48)
[14:38:27 ERROR]:       at dev.simplix.protocolize.velocity.providers.VelocityPacketListenerProvider.lambda$handleInboundPacket$2(VelocityPacketListenerProvider.java:160)
[14:38:27 ERROR]:       at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[14:38:27 ERROR]:       at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[14:38:27 ERROR]:       at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
[14:38:27 ERROR]:       at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
[14:38:27 ERROR]:       at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[14:38:27 ERROR]:       at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[14:38:27 ERROR]:       at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[14:38:27 ERROR]:       at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[14:38:27 ERROR]:       at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[14:38:27 ERROR]:       at dev.simplix.protocolize.velocity.providers.VelocityPacketListenerProvider.handleInboundPacket(VelocityPacketListenerProvider.java:158)
[14:38:27 ERROR]:       at dev.simplix.protocolize.velocity.netty.ProtocolizeDecoderChannelHandler.decode(ProtocolizeDecoderChannelHandler.java:83)
[14:38:27 ERROR]:       at dev.simplix.protocolize.velocity.netty.ProtocolizeDecoderChannelHandler.decode(ProtocolizeDecoderChannelHandler.java:32)
[14:38:27 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:38:27 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89)
[14:38:27 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:38:27 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:38:27 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:38:27 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:38:27 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[14:38:27 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:38:27 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:38:27 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:38:27 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:38:27 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[14:38:27 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[14:38:27 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[14:38:27 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[14:38:27 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[14:38:27 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:38:27 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[14:38:27 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

Working on PR.

**Comment by xrh0905** [comment]
Fixed.
