### ISSUE TITLE
An error occurred while running /vannouncer command

### ISSUE THREAD

**Issue by WhoisDarkyXD** [Matt-MX/AnnouncerVelocity#9]
[04:11:27] [Thread-193207/INFO] [com.velocitypowered.proxy.protocol.packet.chat.CommandHandler]: Exception occurred while running command for WhoisDarkyXD
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command vannouncer for [connected player] WhoisDarkyXD (/ipaddress)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command vannouncer for [connected player] WhoisDarkyXD (/ipaddress)
	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:245) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:272) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
Caused by: java.lang.NoSuchMethodError: 'dev.simplix.protocolize.api.item.ItemStack dev.simplix.protocolize.api.item.ItemStack.displayName(java.lang.Object)'
	at com.mattmx.announcer.util.gui.ItemBuilder.name(ItemBuilder.java:40) ~[?:?]
	at com.mattmx.announcer.guis.AnnouncementsScreen.define(AnnouncementsScreen.java:37) ~[?:?]
	at com.mattmx.announcer.commands.AnnounceCommand.execute(AnnounceCommand.java:54) ~[?:?]
	at com.mattmx.announcer.commands.AnnounceCommand.execute(AnnounceCommand.java:16) ~[?:?]
	at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:228) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:272) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more

The server is on version 1.20.4

**Comment by expdani** [comment]
Same problem
